// SPDX-License-Identifier: MIT
// Resolves every local file reference in the source tree: relative and
// root-absolute ES module specifiers, plus the src/href attributes of the HTML
// pages and partials. Nothing bundles these, so a renamed module or a typo in
// a path is a runtime 404 that only shows up in the browser console, and the
// comparison is case-sensitive because Windows and macOS happily serve
// `core/API.js` for `core/api.js` while the Linux container does not.

import { dirname, resolve } from 'node:path';
import { repoPath, walk, read, rel, existsExact } from './lib.mjs';

const SPECIFIER_RE = /(?:\bfrom\s*|\bimport\s*\(\s*)(['"])([^'"]+)\1/g;
const ATTRIBUTE_RE = /\b(?:src|href)="([^"]+)"/g;

// public/vendor/ is generated by the Docker build (esbuild bundles zxcvbn and
// fflate) and is absent from a fresh clone; /manifest.webmanifest is served by
// routes/manifest.js and has no file of its own.
const GENERATED = ['/vendor/'];
const SERVED_ROUTES = new Set(['/', '/manifest.webmanifest']);

function isExternal(spec) {
  return (
    spec.startsWith('#') ||
    spec.startsWith('http:') ||
    spec.startsWith('https:') ||
    spec.startsWith('//') ||
    spec.startsWith('data:') ||
    spec.startsWith('mailto:')
  );
}

// Returns the absolute path a specifier points at, or null when it is not this
// repo's business to resolve (bare npm package, external URL, generated file).
function targetOf(spec, file, isPublic) {
  if (isExternal(spec)) return null;
  const clean = spec.split(/[?#]/)[0];
  if (!clean) return null;
  if (clean.startsWith('.')) return resolve(dirname(file), clean);
  if (clean.startsWith('/')) {
    if (!isPublic) return null;
    if (SERVED_ROUTES.has(clean)) return null;
    if (GENERATED.some((prefix) => clean.startsWith(prefix))) return null;
    return repoPath('public', clean.slice(1));
  }
  return null;
}

export function run() {
  const errors = [];
  const notes = [];
  const files = [
    ...walk(repoPath('public'), (f) => f.endsWith('.js') || f.endsWith('.html')),
    ...walk(repoPath('server', 'src'), (f) => f.endsWith('.js')),
    ...walk(repoPath('scripts'), (f) => f.endsWith('.js') || f.endsWith('.mjs')),
  ].filter((f) => !rel(f).startsWith('public/vendor/'));

  let checked = 0;
  for (const file of files) {
    const text = read(file);
    const isPublic = rel(file).startsWith('public/');
    const specs = [
      ...[...text.matchAll(SPECIFIER_RE)].map((m) => m[2]),
      ...(file.endsWith('.html') ? [...text.matchAll(ATTRIBUTE_RE)].map((m) => m[1]) : []),
    ];
    for (const spec of specs) {
      const target = targetOf(spec, file, isPublic);
      if (target === null) continue;
      checked += 1;
      if (!existsExact(target)) {
        errors.push(`${rel(file)} references '${spec}', which does not exist`);
      }
    }
  }

  notes.push(`${checked} local references resolved across ${files.length} files`);
  return { name: 'references', errors, notes };
}
